# Generated by Django 5.0.3 on 2024-03-25 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desserts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('composition', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
                ('type_is_hot', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('adres', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=128)),
                ('ranking', models.FloatField(default=0)),
                ('start_of_work', models.TimeField()),
                ('end_of_work', models.TimeField()),
                ('desserts', models.ManyToManyField(to='cafe.desserts')),
                ('drinks', models.ManyToManyField(to='cafe.drinks')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_cafes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.coffeeshop')),
                ('favourite_desserts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.desserts')),
                ('favourite_drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.drinks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('coffees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.coffeeshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('user', 'coffees'), name='feedback_constraints'),
        ),
    ]
