# Generated by Django 5.0.3 on 2024-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Kawiarnia'),
        ),
        migrations.AlterField(
            model_name='desserts',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Deser'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Napój'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='type_is_hot',
            field=models.BooleanField(default=True, verbose_name='Hot drink'),
        ),
    ]
