# Generated by Django 5.0.3 on 2024-04-04 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_coffeeshop_name_alter_desserts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favourite_cafes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favourite_desserts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.desserts'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='favourite_drinks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.drinks'),
        ),
    ]
